#!/bin/bash

val="[\n\tname: '$1',\n\trootprojectname: '$2',\n\tgiturl: '$3',\n\tdashboard: $4,\n\tendpoint: '$5',\n\tdefault_branch: '$6',\n\twebhook_token: '$7',\n\tstageTemplates: '$8'\n]"
echo -e $val  > temp
